#development:
  stripe_secret_key: 'sk_test_wHMjQkNK1tkb4hrEJV1uDAFN00QoBprMuU' 
  #'sk_test_BRPpISwsTFnO5ih1WlxbvSkz'
  stripe_publishable_key: pk_test_TYooMQauvdEDq54NiTphI7jx
    #'pk_test_ityX5pdAjy1Pafnmggi18tND00HSzcZ6uS'
  #'pk_test_SAfpkFB2WVKLbQVukGCTVq5Z'
  #Publishable pk_test_ityX5pdAjy1Pafnmggi18tND00HSzcZ6uS
  #Secret sk_test_wHMjQkNK1tkb4hrEJV1uDAFN00QoBprMuU

#production:
#  stripe_secret_key: 'sk_live_aLvPhyGtUwlLSHvms3KhCdrL'
#  stripe_publishable_key: 'pk_live_nbTqsm8Gg0eHGrQVRbWnjlyN'



#Mabeth
#Publishable key
#pk_test_ityX5pdAjy1Pafnmggi18tND00HSzcZ6uS
#Secret key
#sk_test_wHMjQkNK1tkb4hrEJV1uDAFN00QoBprMuU